


# ui
BAR_HEIGHT =  20
FEEDING_BAR_WIDTH = 150
HAPPINESS_BAR_WIDTH = 150
CLEARNESS_BAR_WIDTH = 150
UI_FONT = 'images/font/joystix.ttf'
UI_FONT_SIZE = 18
#general colors
WATER_COLOR = '#71ddee'
UI_BG_COLOR = '#222222'
UI_BORDER_COLOR = '#111111'
TEXT_COLOR = '#000000'

#ui colors 
SATIETY_COLOR = 'yellow'
HAPPY_COLOR = 'red'
CLEAR_COLOR = 'green'
UI_BORDER_COLOR_ACTIVE = 'gold'



#SCREEN
SCREEN_HEIGHT = 500
SCREEN_WIDTH = 1000
